"""
Crew Tasks Formulation Module
Defines the sequential tasks that the agents will execute.
"""

from crewai import Task


def create_intake_task(agent, user_query: str) -> Task:
    """Analyze query and build student profile."""
    return Task(
        description=(
            f"Analyze the following student query: '{user_query}'\n\n"
            "Use your tools to parse the query into a structured student profile. "
            "Identify the query type, completed courses, target program, target courses, "
            "grades, term, and max courses. Highlight any CRITICAL missing information "
            "needed to accurately answer the question."
        ),
        expected_output=(
            "A structured student profile, the classified query type, and "
            "a list of clarifying questions (if information is missing)."
        ),
        agent=agent,
    )


def create_retriever_task(agent, user_query: str) -> Task:
    """Search catalog vector store based on the profile and query."""
    return Task(
        description=(
            f"Based on the student's original query: '{user_query}'\n"
            "Search the course catalog using the vector_search tool to find "
            "the specific prerequisites, program requirements, course descriptions, "
            "and academic policies needed to answer the query. "
            "When searching for prerequisites, search for the specific course codes. "
            "When searching for programs, search for degree requirements."
        ),
        expected_output=(
            "A comprehensive compilation of exact catalog text excerpts relevant to "
            "the query, with each excerpt citing its source file, page, and section."
        ),
        agent=agent,
    )


def create_rule_extraction_task(agent) -> Task:
    """Interpret raw catalog quotes into structured rules."""
    return Task(
        description=(
            "Review the catalog excerpts found by the Catalog Retriever. "
            "Extract all relevant academic rules into a structured format. "
            "Identify ALL prerequisite chains (A -> B -> C), co-requisites, "
            "minimum grades, and 'either/or' options. "
            "Pay close attention to transitive dependencies."
        ),
        expected_output=(
            "A clean, structured list of the exact prerequisites, policies, "
            "and requirements that govern the student's request, linked "
            "to their source citations."
        ),
        agent=agent,
    )


def create_planner_task(agent, user_query: str) -> Task:
    """Generate final course plan with citations."""
    return Task(
        description=(
            f"Address the student's original query: '{user_query}'\n\n"
            "Using the structured student profile from the Intake Analyst, "
            "and the structured academic rules from the Rule Extractor, "
            "generate the final response. Use transitive reasoning to check "
            "eligibility. "
            "You MUST output exactly in the format specified in your system prompt "
            "(Answer/Plan, Why, Citations, Clarifying questions, Assumptions/Not in catalog)."
        ),
        expected_output=(
            "The final advice or course plan for the student, strictly adhering "
            "to the required 5-section format with comprehensive citations."
        ),
        agent=agent,
    )


def create_verifier_task(agent) -> Task:
    """Audit the planner's response."""
    return Task(
        description=(
            "Review the final response generated by the Course Planning Expert. "
            "Verify that EVERY single claim is backed by a specific citation. "
            "Ensure the prerequisite logic and transitive chains are flawless. "
            "Check that the 5-part output format is strictly followed. "
            "If any unsupported claim exists, or if info not in the catalog was stated as fact, "
            "fix it directly."
        ),
        expected_output=(
            "The verified, corrected final response ready to be presented to the student, "
            "adhering to all safety and citation guidelines."
        ),
        agent=agent,
    )
