"""
Verifier / Auditor Agent
Checks responses for unsupported claims, missing citations, and prereq errors.
"""

from crewai import Agent
from rag.prompt_templates import VERIFIER_AGENT_SYSTEM_PROMPT


def create_verifier_agent(llm, tools=None) -> Agent:
    """
    Create the Verifier/Auditor Agent.
    
    Role: Review and verify the planner's response for accuracy,
    citation completeness, and correct prerequisite logic.
    """
    agent_tools = tools or []
    
    return Agent(
        role="Academic Compliance Auditor",
        goal=(
            "Review the course plan or answer generated by the Planner Agent. "
            "Verify that: (1) every factual claim has a supporting citation, "
            "(2) prerequisite logic is correct (including transitive chains), "
            "(3) the response follows the required output format, "
            "(4) no information is stated as fact when it's not in the catalog, "
            "(5) clarifying questions are included when student info is incomplete. "
            "Flag any issues and provide a corrected response if needed."
        ),
        backstory=(
            "You are a quality assurance specialist for academic advising. "
            "You have a keen eye for unsupported claims, logical errors in "
            "prerequisite reasoning, and formatting issues. You understand "
            "that incorrect advice can lead to students enrolling in courses "
            "they're not eligible for, so accuracy is paramount. You verify "
            "every citation against the source material and check that "
            "the response appropriately abstains when information is not "
            "available in the catalog."
        ),
        tools=agent_tools,
        llm=llm,
        verbose=True,
        allow_delegation=False,
        system_prompt=VERIFIER_AGENT_SYSTEM_PROMPT,
    )
